export UPSTREAM_DIR=meta-upstream
export UPSTREAM_REPO=git@github.com:PolyethyleneMC/meta-upstream.git
export PMC_DIR=pmeta
export PMC_REPO=git@github.com:PolyetyleneMC/meta.git
export BRANCH_master=master
export BRANCH_develop=develop
export DEPLOY_TO_S3=false
export DEPLOY_FOLDER_master=/app/public/v1
export DEPLOY_FOLDER_develop=/app/public/dev
export DEPLOY_FOLDER_USER=http
export DEPLOY_FOLDER_GROUP=http
export MODE=master
export GIT_AUTHOR_NAME="PolyetyleneMC Bot"
export GIT_AUTHOR_EMAIL="polyetylene@notanactualemail.com"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
export DEPLOY_TO_FOLDER=false
export DEPLOY_TO_GIT=true
# export GIT_SSH_COMMAND="ssh -i ${BASEDIR}/config/deploy.key"
